FROM ruby:3.3.1-bullseye

# Install essential Linux packages for development plus node.js
RUN apt-get update -qq
RUN apt-get install -y --no-install-recommends git build-essential curl libpq-dev cmake gnupg pkg-config wget postgresql-client
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/deb.nodesource.com.gpg && \
    curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/dl.yarnpkg.com.gpg && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list   && \
    echo "deb https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && \
    apt-get --no-install-recommends install nodejs yarn
